project:
  type: website
  resources:
    - assets/**

execute:
  freeze: auto
  output-dir: _freeze

website:
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Navigation"
        href: navigation.qmd
      - text: "PhD"
        href: phd.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual