project:
  type: website
  resources:
    - assets/**

execute:
  freeze: auto

website:
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "PhD"
        href: phd.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

include-in-header:
  - text: |
      <script defer src="https://cdn.jsdelivr.net/npm/typed.js@2.0.12"></script>