---
title: "Navigating data stories?"
subtitle: "Scroll through this slide deck to find out how"
format:
  revealjs:
    theme: black
    controls: true
    controlsLayout: edges
    controlsBackArrows: visible
    controlsTutorial: true
    preview-links: auto
    progress: true
    slideNumber: true
    hash: true
    navigationMode: default
---

# Art {background="#46e7fd"}

## Art on the large screen {auto-animate="true" auto-animate-easing="ease-in-out"}

When viewed on a large screen, the art piece is the first column of the data story.

<br/>

<br/>

:::::: r-hstack
::: {data-id="box1" auto-animate-delay="0" style="background:#46e7fd; width:200px; height:150px; margin:10px; border-radius:12px; display:flex; align-items:center; justify-content:center; color:#000; font-weight:bold;"}
Art
:::

::: {data-id="box2" auto-animate-delay="0.1" style="background:#4739a2; width:200px; height:150px; margin:10px; border-radius:12px; display:flex; align-items:center; justify-content:center; color:#fff; font-weight:bold;"}
:::

::: {data-id="box3" auto-animate-delay="0.2" style="background:#e18b22; width:200px; height:150px; margin:10px; border-radius:12px; display:flex; align-items:center; justify-content:center; text-align:center; color:#000; font-weight:bold; font-size:1.5rem;"}
:::
::::::

## Art on the small screen {auto-animate="true" auto-animate-easing="ease-in-out"}

When viewed on a small screen, the art piece is the first row of the data story.

<br/>

<br/>

:::::: r-vstack
::: {data-id="box1" style="background:#46e7fd; width:80%; height:80px; margin:6px auto; border-radius:12px; display:flex; align-items:center; justify-content:center; color:#000; font-weight:bold;"}
Art
:::

::: {data-id="box2" style="background:#4739a2; width:80%; height:80px; margin:6px auto; border-radius:12px; display:flex; align-items:center; justify-content:center; color:#fff; font-weight:bold;"}
:::

::: {data-id="box3" style="background:#e18b22; width:80%; height:80px; margin:6px auto; border-radius:12px; display:flex; align-items:center; justify-content:center; color:#000; font-weight:bold;"}
:::
::::::

## Interacting with the art piece

::: {.fragment .fade-in-then-semi-out}
Artistic and abstract interpretations made from the data
:::

<br/>

::: {.fragment .fade-in-then-semi-out}
Click on the art piece to expand and see the corresponding link
:::

<br/>

::: {.fragment .fade-in-then-semi-out}
Step [behind the curtain](https://commons.wikimedia.org/wiki/File:The_call.png){preview-link="true"} (i.e. click the link) to uncover the meaning of the piece on Wikimedia Commons
:::

<br/>

::: {.fragment .fade-in-then-semi-out}
Click the artwork again to go back to all three sections
:::

# Poetry {background="#4739a2"}

## Poems on the large screen {auto-animate="true" auto-animate-easing="ease-in-out"}

When viewed on a large screen, the peom is the second column of the data story.

<br/>

<br/>

:::::: r-hstack
::: {data-id="box1" auto-animate-delay="0" style="background:#46e7fd; width:200px; height:150px; margin:10px; border-radius:12px; display:flex; align-items:center; justify-content:center; color:#000; font-weight:bold;"}
:::

::: {data-id="box2" auto-animate-delay="0.1" style="background:#4739a2; width:200px; height:150px; margin:10px; border-radius:12px; display:flex; align-items:center; justify-content:center; color:#fff; font-weight:bold;"}
Poetry
:::

::: {data-id="box3" auto-animate-delay="0.2" style="background:#e18b22; width:200px; height:150px; margin:10px; border-radius:12px; display:flex; align-items:center; justify-content:center; text-align:center; color:#000; font-weight:bold; font-size:1.5rem;"}
:::
::::::

## Poems on the small screen {auto-animate="true" auto-animate-easing="ease-in-out"}

When viewed on a small screen, the poem is the second row of the data story.

<br/>

<br/>

:::::: r-vstack
::: {data-id="box1" style="background:#46e7fd; width:80%; height:80px; margin:6px auto; border-radius:12px; display:flex; align-items:center; justify-content:center; color:#000; font-weight:bold;"}
:::

::: {data-id="box2" style="background:#4739a2; width:80%; height:80px; margin:6px auto; border-radius:12px; display:flex; align-items:center; justify-content:center; color:#fff; font-weight:bold;"}
Poetry
:::

::: {data-id="box3" style="background:#e18b22; width:80%; height:80px; margin:6px auto; border-radius:12px; display:flex; align-items:center; justify-content:center; color:#000; font-weight:bold;"}
:::
::::::

## Interacting with the poem

::: {.fragment .fade-in-then-semi-out}
A poetic lens on the data, highlighting one or more key messages in verse.
:::

<br/>

::: {.fragment .fade-in-then-semi-out}
Click on the word to reveal the poem and the corresponding link
:::

<br/>

::: {.fragment .fade-in-then-semi-out}
Get [more words on the matter](https://www.sciencedirect.com/science/article/pii/S0033350625002938){target="_blank" rel="noopener"} and read the publication or manuscript
:::

<br/>

::: {.fragment .fade-in-then-semi-out}
Click the poem to go back to all three sections
:::

# Data Visualisation {background="#e18b22"}

## Data Visuals on the large screen {auto-animate="true" auto-animate-easing="ease-in-out"}

When viewed on a large screen, the data visuals are on the last column of the data story.

<br/>

<br/>

:::::: r-hstack
::: {data-id="box1" auto-animate-delay="0" style="background:#46e7fd; width:200px; height:150px; margin:10px; border-radius:12px; display:flex; align-items:center; justify-content:center; color:#000; font-weight:bold;"}
:::

::: {data-id="box2" auto-animate-delay="0.1" style="background:#4739a2; width:200px; height:150px; margin:10px; border-radius:12px; display:flex; align-items:center; justify-content:center; color:#fff; font-weight:bold;"}
:::

::: {data-id="box3" auto-animate-delay="0.2" style="background:#e18b22; width:200px; height:150px; margin:10px; border-radius:12px; display:flex; align-items:center; justify-content:center; text-align:center; color:#000; font-weight:bold; font-size:1.5rem;"}
Data Visualisation
:::
::::::

## Data Visuals on the small screen {auto-animate="true" auto-animate-easing="ease-in-out"}

When viewed on a small screen, the data visuals are on the last row of the data story.

<br/>

<br/>

:::::: r-vstack
::: {data-id="box1" style="background:#46e7fd; width:80%; height:80px; margin:6px auto; border-radius:12px; display:flex; align-items:center; justify-content:center; color:#000; font-weight:bold;"}
:::

::: {data-id="box2" style="background:#4739a2; width:80%; height:80px; margin:6px auto; border-radius:12px; display:flex; align-items:center; justify-content:center; color:#fff; font-weight:bold;"}
:::

::: {data-id="box3" style="background:#e18b22; width:80%; height:80px; margin:6px auto; border-radius:12px; display:flex; align-items:center; justify-content:center; color:#000; font-weight:bold;"}
Data Visualisation
:::
::::::

## Interacting with the data visual

::: {.fragment .fade-in-then-semi-out}
Charts, graphs or graphics, presenting key insights from data
:::

<br/>

::: {.fragment .fade-in-then-semi-out}
Click on the graphic to zoom in and see the corresponding link
:::

<br/>

::: {.fragment .fade-in-then-semi-out}
Say [open seasame](https://en.wikipedia.org/wiki/Center_for_Open_Science#Open_Science_Framework){preview-link="true"} (i.e. click the link) to go to the Open Science Framework repository for the body of work, and see all metadata and code associated with data and analyses
:::

<br/>

::: {.fragment .fade-in-then-semi-out}
Click the white space outside the graphic to go back to all three sections
:::

# Let's go {background="#008000"}

## Where are the data stories? {background-image="img/follow_rabbit.jpg"}

<br/>

<br/>

Click [here](https://varthai.netlify.app/navigation#jump-to-some-data-stories) to jump to data stories

::: footer
Photo by [Andy Brunner](https://unsplash.com/@andy_brunner?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash) on [Unsplash](https://unsplash.com/photos/white-rabbit-on-green-grass-field-A10ZZ_oBBME?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash)
:::
      